name: umiuni2d_sprite_html5
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: kyorohiro <email@example.com>

environment:
  sdk: '>=2.0.0-dev.22.0 <2.0.0'
dependencies:
  vector_math: 2.0.5
  umiuni2d_sprite:
    git:
      url: https://github.com/kyorohiro/umiuni2d_sprite.git
      ref: v0.0.3

dev_dependencies:
  test: ^0.12.0
